version: '3.9'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn webfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.local.staging
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.local.staging.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
     - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: