# Generated by Django 4.1.3 on 2022-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=300)),
                ('image', models.FilePathField(path='home/images')),
                ('link', models.URLField()),
            ],
        ),
    ]
