# Generated by Django 4.1.3 on 2022-11-26 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_projects_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
